# 1 NumPy介绍

## 1.1 前言 

## 1.2 多维数组 

### 1.2.1 一维数组 

In [1]:
import numpy as np

my_list = [0,1,2,3,4,5,6]
my_arr = np.array(my_list)

my_arr

array([0, 1, 2, 3, 4, 5, 6])

In [7]:
# 可以通过索引对数组进行遍历

# my_arr[2: 4]
print("my_arr[0]", my_arr[0])
print("my_arr[1]", my_arr[1])

my_arr[0] 0
my_arr[1] 1


### 1.2.2 二维数组 

In [8]:
import numpy as np

my_list = [[0, 1, 2], [3, 4, 5]]
my_arr = np.array(my_list)

my_arr

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
# 通过索引寻找
my_arr[0][1]

1

## 1.3 ndarray的优势

### 1.3.1 更少的存储空间 

### 1.3.2 更快的处理速度 

### 1.3.3 更方便的操作 

# 2 ndarray的创建及属性

## 2.1 ndarray的创建及获取属性 

### 2.1.1 查看类型 

#### 2.1.1.1 查看ndarray的类型 

In [10]:
import numpy as np

my_list = [1,2,3,4,5,6]
my_arr = np.array(my_list)

type(my_arr)

numpy.ndarray

#### 2.1.1.2 查看ndarray中元素的类型 

In [11]:
import numpy as np

my_list = [1,2,3,4,5,6]
my_arr = np.array(my_list)

my_arr.dtype

dtype('int32')

### 2.1.2 查看维度信息 

#### 2.1.2.1 查看维度数 

In [13]:
import numpy as np

my_list = [[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]]
my_arr = np.array(my_list)

my_arr.ndim

2

#### 2.1.2.2 查看数组大小

In [14]:
import numpy as np

my_list = [[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]]
my_arr = np.array(my_list)

my_arr.size

6

#### 2.1.2.3 查看各维度大小 

In [15]:
import numpy as np

my_list = [[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]]
my_arr = np.array(my_list)

my_arr.shape

(2, 3)

### 2.1.3 查看元素信息 

#### 2.1.3.1 查看元素占用的存储空间

In [16]:
import numpy as np

my_list = [[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]]
my_arr = np.array(my_list)

my_arr.itemsize

8

## 2.2 使用函数创建ndarray 

### 2.2.1 arange  函数

In [22]:
import numpy as np

my_arr = np.arange(0, 12)

my_arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
my_arr2 = np.arange(0, 12, 3) # 步长为3

my_arr2

array([0, 3, 6, 9])

In [24]:
my_arr3 = np.arange(0, 4, 0.5)

my_arr3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [25]:
# reshape()
my_arr4 = np.arange(0, 12).reshape(3, 4)

my_arr4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### 2.2.2 linspace 函数

In [26]:
import numpy as np

my_arr = np.linspace(0, 10, 5)

my_arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### 2.2.3 zeros 函数

In [30]:
import numpy as np

my_arr = np.zeros((2,3)) # 参数为元组

my_arr

array([[0., 0., 0.],
       [0., 0., 0.]])

### 2.2.4 ones 函数 

In [32]:
import numpy as np

my_arr = np.ones((2,3)) # 参数为元组

my_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

### 2.2.5 random 函数

In [36]:
import numpy as np

my_arr = np.random.random(3)

my_arr

array([0.65617436, 0.42394644, 0.14802637])

In [37]:
import numpy as np

my_arr = np.random.random((2,3))

my_arr

array([[0.51824239, 0.99705087, 0.69276689],
       [0.59058823, 0.86602074, 0.59978448]])

# 3 ndarray的基本操作

## 3.1 ndarray和标量之间的运算 

### 3.1.1 加法运算 

In [38]:
import numpy as np

my_list = [1,2,3,4,5,6]
my_arr = np.array(my_list)

my_arr = my_arr + 3

my_arr

array([4, 5, 6, 7, 8, 9])

### 3.1.2 减法运算 

In [39]:
import numpy as np

my_list = [1,2,3,4,5,6]
my_arr = np.array(my_list)

my_arr = my_arr - 3

my_arr

array([-2, -1,  0,  1,  2,  3])

### 3.1.3 乘法运算 

### 3.1.4 除法运算 

In [46]:
# 需要先把ndarray元素转化为float64类型
import numpy as np

my_list = [1,2,3,4,5,6]
my_arr = np.array(my_list, dtype=np.float64)

my_arr = my_arr / 3

my_arr

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667,
       2.        ])

### 3.1.5 取余运算 

In [48]:
import numpy as np

my_list = [1,2,3,4,5,6]
my_arr = np.array(my_list)

my_arr = my_arr % 3

my_arr

array([1, 2, 0, 1, 2, 0], dtype=int32)

### 3.1.6 取整运算

In [49]:
import numpy as np

my_list = [1,2,3,4,5,6]
my_arr = np.array(my_list)

my_arr = my_arr // 3

my_arr

array([0, 0, 1, 1, 1, 2], dtype=int32)

## 3.2 ndarray之间的运算 

### 3.2.1 一维数组 

#### 3.2.1.1 加法运算 

In [55]:
import numpy as np

my_list1 = [1,2,3,4,5,6]
my_arr1 = np.array(my_list1)

my_list2 = [1,2,3,4,5,6]
my_arr2 = np.array(my_list2, dtype=np.float64)

sum_arr = my_arr1 + my_arr2

sum_arr

array([ 2.,  4.,  6.,  8., 10., 12.])

#### 3.2.1.1 加法运算 

#### 3.2.1.1 加法运算 

#### 3.2.1.1 加法运算 

### 3.2.2 多维数组 

## 3.3 ndarray的点乘 

In [63]:
import numpy as np

my_arr1 = np.arange(1, 10).reshape((3,3))
my_arr2 = np.ones((3,3))

# dot_arr = np.dot(my_arr1, my_arr2)
dot_arr = my_arr1.dot(my_arr2)

# dot_arr
print(my_arr1)
print()
print(my_arr2)

dot_arr

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[ 6.,  6.,  6.],
       [15., 15., 15.],
       [24., 24., 24.]])

## 3.4 一些函数 

### 3.4.1 一维数组

#### 3.4.1.1 sqrt() 函数

In [67]:
# 求数组中各个元素的平方根
import numpy as np

my_arr = np.arange(1,7)

np.sqrt(my_arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

#### 3.4.1.2 log() 函数

In [69]:
# 求数组中各个元素以 e 为底的对数
import numpy as np

my_arr = np.arange(1,7)

np.log(my_arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947])

#### 3.4.1.3 sin() 函数

In [70]:
# 求数组中各个元素（元素的值代表弧度）的正弦值

#### 3.4.1.4 cos() 函数

In [71]:
# 求数组中各个元素（元素的值代表弧度）的余弦值

#### 3.4.1.5 sum() 函数

In [72]:
# 求数组中各个元素的和

#### 3.4.1.6 min() 函数

In [ ]:
# 求数组中各个元素中的最小值

#### 3.4.1.6 sum() 函数

In [ ]:
# 求数组中各个元素中的最大值

#### 3.4.1.8 mean() 函数

In [74]:
# 求数组中各个元素的平均值

#### 3.4.1.9 std() 函数

In [75]:
# 求数组中各个元素的标准差

#### 3.4.1.10cumsum() 函数

In [77]:
# 求数组中各个元素的累计和，得到的是一个和原来的数组维度相同的数组
import numpy as np

my_arr = np.arange(1, 7)

print(my_arr)
np.cumsum(my_arr)

[1 2 3 4 5 6]


array([ 1,  3,  6, 10, 15, 21])

#### 3.4.1.11 cumprod() 函数

In [78]:
# 求数组中各个元素的累计积，得到的是一个和原来的数组维度相同的数组
import numpy as np

my_arr = np.arange(1, 7)

print(my_arr)
np.cumprod(my_arr)

[1 2 3 4 5 6]


array([  1,   2,   6,  24, 120, 720])

### 3.4.2 二维数组

#  4 ndarray的索引、切片和遍历

## 4.1 索引

### 4.1.1 一维数组的索引 

In [79]:
import numpy as np

my_arr = np.arange(1, 10)

my_arr[[0, 1, 2]]

array([1, 2, 3])

### 4.1.2 二维数组的索引

In [92]:
import numpy as np

my_arr = np.arange(1, 10).reshape((3,3))

print(my_arr)

my_arr[1, [1,2]] # 第1行的第1列和第2列

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[4, 5, 6],
       [7, 8, 9]])

### 4.1.3  布尔索引

In [96]:
import numpy as np

my_arr = np.random.random(9)

my_arr < 0.5

array([False,  True,  True,  True, False, False,  True, False, False])

In [95]:
import numpy as np

my_arr = np.random.random(9)

my_arr[my_arr < 0.5]

array([0.04741079, 0.0844618 , 0.37873655])

In [105]:
import numpy as np

my_arr = np.random.random((4,4))
names = np.array(['Bob', 'Joe', "Will", "Bob"])

print(names == 'Bob')

my_arr[names == 'Bob']

[ True False False  True]


array([[0.16031905, 0.89137832, 0.40728348, 0.67205155],
       [0.79697799, 0.05965324, 0.79181732, 0.45003989]])

## 4.2 切片 

In [107]:
# 一维
import numpy as np

my_arr = np.arange(9)

my_arr[1: 5]

array([1, 2, 3, 4])

In [111]:
# 二维
import numpy as np

my_arr = np.arange(1, 10).reshape((3, 3))

print(my_arr)

my_arr[:, 2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([3, 6, 9])

## 4.3 遍历 

In [ ]:
# for循环遍历

In [116]:
# 将多维数组平铺成一维数组,然后遍历
import numpy as np

my_arr = np.arange(9).reshape((3, 3))

print(my_arr.flatten())

for i in my_arr.flatten():
    print(i)

[0 1 2 3 4 5 6 7 8]
0
1
2
3
4
5
6
7
8


In [119]:
# 行优先遍历
import numpy as np

my_arr = np.arange(6).reshape((2, 3))

print(my_arr)
for i in np.nditer(my_arr, order='C'):
    print(i)

[[0 1 2]
 [3 4 5]]
0
1
2
3
4
5


In [120]:
# 列优先遍历
import numpy as np

my_arr = np.arange(6).reshape((2, 3))

print(my_arr)
for i in np.nditer(my_arr, order='F'):
    print(i)

[[0 1 2]
 [3 4 5]]
0
3
1
4
2
5


# 5 ndarray的重塑、组合和拆分

## 5.1 重塑 

In [125]:
import numpy as np

my_arr = np.random.random(12)

my_arr.shape

(12,)

In [124]:
my_arr.shape = (3,4)

my_arr.shape

(3, 4)

In [127]:
# 重新改成一维数组
my_arr.ravel()

my_arr.shape

(12,)

## 5.2 组合 

In [131]:
import numpy as np

my_arr1 = np.ones((3,3))
my_arr2 = np.zeros((4,3))

print(my_arr1)
print(my_arr2)

# np.vstack((my_arr1, my_arr2))
np.row_stack((my_arr1, my_arr2))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [130]:
import numpy as np

my_arr1 = np.ones((3,3))
my_arr2 = np.zeros((3,4))

# np.column_stack((my_arr1, my_arr2))
np.hstack((my_arr1, my_arr2))

array([[1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0.]])

## 5.3 拆分 

In [136]:
# 水平拆分
import numpy as np

my_arr1 = np.arange(0, 16).reshape((4, 4))

print(my_arr1)

[my_arr2, my_arr3] = np.hsplit(my_arr1, 2) # 拆成左右两部分 

print(my_arr2)
print(my_arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1]
 [ 5]
 [ 9]
 [13]]


In [139]:
# 水平拆分
import numpy as np

my_arr1 = np.arange(0, 16).reshape((4, 4))

print(my_arr1)

[my_arr2, my_arr3] = np.vsplit(my_arr1, 2) # 拆成上下两部分 

print(my_arr2)
print(my_arr3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [141]:
import numpy as np

my_arr1 = np.arange(0, 16).reshape((4, 4))

# 将第一行,拆成
[my_arr2, my_arr3, my_arr4] = np.split(my_arr1, [1, 3], axis=1)

print(my_arr2)
print(my_arr3)
print(my_arr4)

[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]
